### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed

### ISSUE THREAD

**Issue by M3M0RYK1TT3N** [M3M0RYK1TT3N/discord-selfbot#2]
Traceback (most recent call last):
  File "main.py", line 387, in <module>
    client.run("token", bot=True)
  File "/home/runner/ImaginativeStripedPatch/venv/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/runner/ImaginativeStripedPatch/venv/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/runner/ImaginativeStripedPatch/venv/lib/python3.8/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/home/runner/ImaginativeStripedPatch/venv/lib/python3.8/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/home/runner/ImaginativeStripedPatch/venv/lib/python3.8/site-packages/discord/http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

error from the console
discord has banned the bot but i will work on another way around this

**Comment by nana640** [comment]
issue is now fixed
